import { useEffect, useRef, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { ArrowRight, ChevronLeft, RotateCcw, Send, Sparkles } from 'lucide-react';
import { analyzeSituation } from './services/api';
import { PixelDecor } from './components/PixelDecor';
import { IntroFlow } from './components/IntroFlow';
import { chooseNext, emptyFeatures, getContextNote, getOpeningChoice, inferFromText, makeReaction } from './engine/conversationEngine';
import { buildTimeline, defaultProfile, demoStory, deriveBroAnalysis, getDecisionOptions, getGreeting, getOverthinkingCheck, modeChoices, saveStory, simulateDecision } from './engine/broModeEngine';

const starters = ["Someone's suddenly texting differently 👀", "I'm confused about the vibes", "They said yes and now they're disappearing", "I think I'm putting in way more effort", "It's complicated 💀", 'Let me explain from the beginning'];
const patternNames = { ghosting_after_yes: 'Ghosting after initial interest', mixed_signals: 'Mixed signals', one_sided_effort: 'One-sided effort', hot_and_cold: 'Hot and cold', breadcrumbing: 'Breadcrumbing' };
const outcomeNames = { ghosted: 'Ghosted', rejected: 'Rejected', not_available: 'Not available' };

function Avatar({ mood = 'neutral' }) { return <div className={`pixel-avatar ${mood}`} aria-hidden="true">{mood === 'positive' ? '💚' : mood === 'concern' ? '🚩' : mood === 'ghost' ? '👻' : mood === 'thinking' ? '💭' : '❤️'}</div>; }
function TypingIndicator() { return <motion.div className="typing" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><Avatar mood="thinking" /><span>bestie is typing <i /> <i /> <i /></span></motion.div>; }
function Bubble({ message, assistant, mood }) { return <motion.div className={`message-row ${assistant ? 'assistant-row' : 'user-row'}`} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .25 }}><div className="message-wrap">{assistant && <Avatar mood={mood} />}<div className={`bubble ${assistant ? 'assistant-bubble' : 'user-bubble'}`}>{message}</div></div></motion.div>; }

function Opening({ onStart }) {
  const [custom, setCustom] = useState('');
  return <main className="chat-page opening-page"><div className="chat-shell"><div className="chat-top"><span className="brand"><span className="brand-heart">♥</span> DON'T REPEAT</span><span className="online"><span /> listening mode</span></div><div className="opening-content"><div className="opening-avatar"><Avatar /></div><span className="kicker">THE LORE DESK · PRIVATE CHAT</span><h1>Okay babe,<br /><em>spill.</em> What's going on?</h1><p>We listen, remember the pattern, and do not judge.</p><div className="starter-list">{starters.map((starter) => <button key={starter} onClick={() => onStart(starter)}>{starter}<ArrowRight size={15} /></button>)}</div><div className="free-input"><input value={custom} onChange={(event) => setCustom(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && custom.trim() && onStart(custom)} placeholder="Or add to the lore..." /><button aria-label="Send your story" onClick={() => custom.trim() && onStart(custom)}><Send size={17} /></button></div><small>No names or screenshots needed. Just the vibe.</small></div></div></main>;
}

function Chat({ onDone, onCancel, initialFeatures, openingMessage }) {
  const [features, setFeatures] = useState({ ...initialFeatures });
  const [messages, setMessages] = useState([{ assistant: true, message: 'Okay babe, spill. What is going on?', mood: 'neutral' }, ...(openingMessage ? [{ assistant: false, message: openingMessage }] : []), { assistant: true, message: openingMessage ? 'Okay, I have that part of the lore. Let us zoom in one thing at a time.' : 'Start wherever makes sense. I am listening, and I will remember the lore.', mood: 'neutral' }]);
  const [question, setQuestion] = useState(chooseNext(initialFeatures));
  const [typing, setTyping] = useState(false); const [custom, setCustom] = useState(''); const [history, setHistory] = useState([]); const endRef = useRef(null);
  useEffect(() => { endRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [messages, typing, question]);
  const ask = (value, label = value) => { const inferred = inferFromText(label); const nextFeatures = { ...features, ...inferred, [question.key]: value }; setFeatures(nextFeatures); setHistory((items) => [...items, question.key]); setMessages((items) => [...items, { assistant: false, message: label }]); setQuestion(null); setCustom(''); setTyping(true); const next = chooseNext(nextFeatures, history); const reaction = makeReaction(value, nextFeatures, question, history.length); const note = getContextNote(nextFeatures); window.setTimeout(() => { setTyping(false); setMessages((items) => [...items, { assistant: true, message: reaction, mood: nextFeatures.reply_change === 'Consistent' ? 'positive' : nextFeatures.reply_change === 'Randomly disappears' ? 'ghost' : 'neutral' }, ...(note ? [{ assistant: true, message: note, mood: 'concern' }] : [])]); if (next) window.setTimeout(() => setQuestion(next), 220); else window.setTimeout(() => onDone(nextFeatures), 520); }, 520); };
  const sendCustom = () => { if (!custom.trim() || !question) return; const inferred = inferFromText(custom); ask(inferred[question.key] || custom, custom); };
  return <main className="chat-page"><div className="chat-shell conversation-shell"><div className="chat-top"><button className="back-button" onClick={onCancel}><ChevronLeft size={16} /> leave chat</button><div className="chat-status"><Avatar mood={typing ? 'thinking' : 'neutral'} /><span><strong>your emotionally intelligent bestie</strong><small>{typing ? 'thinking...' : 'online · remembering the lore'}</small></span></div><span className="progress-copy">{history.length < 4 ? 'getting the picture...' : history.length < 8 ? 'connecting the dots...' : 'almost enough tea ☕'}</span></div><div className="conversation"><AnimatePresence>{messages.map((item, index) => <Bubble key={`${index}-${item.message}`} message={item.message} assistant={item.assistant} mood={item.mood} />)}</AnimatePresence>{typing && <TypingIndicator />}<div ref={endRef} /></div>{question && !typing && <motion.div className="reply-dock" initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} key={question.key}><div className="question-line"><span className="kicker">ONE THING</span><strong>{question.text}</strong></div><div className="quick-replies">{question.options.map(([label, value]) => <button key={label} onClick={() => ask(value, label)}>{label}</button>)}</div><div className="free-input compact"><input value={custom} onChange={(event) => setCustom(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && sendCustom()} placeholder="Something else? add to the lore..." /><button onClick={sendCustom} aria-label="Send response"><Send size={16} /></button></div></motion.div>}</div></main>;
}

function Loading({ onComplete, features }) {
  const lines = ['opening the group chat archives...', 'jk 😭 checking the historical data', 'matching the patterns...', 'looking for similar situations...', 'okay... I found something 👀']; const [line, setLine] = useState(0);
  useEffect(() => { const interval = window.setInterval(() => setLine((value) => value + 1), 620); const timeout = window.setTimeout(() => onComplete(features), 3100); return () => { window.clearInterval(interval); window.clearTimeout(timeout); }; }, [features, onComplete]);
  return <main className="loading-page"><Avatar mood="thinking" /><span className="kicker">RECEIPTS IN PROGRESS</span><h2>{lines[Math.min(line, lines.length - 1)]}</h2><div className="loading-bar"><motion.div initial={{ width: 0 }} animate={{ width: '100%' }} transition={{ duration: 3 }} /></div><p>People are not algorithms. We are looking for context, not a prophecy.</p></main>;
}

function Results({ result, features, onReset }) {
  const warning = result.warning || 'MEDIUM'; const high = warning === 'HIGH'; const low = warning === 'LOW'; const intro = high ? "Okay babe... I'm seeing the pattern. 👀" : low ? 'Wait... consistent replies, equal effort, no major mixed signals?' : "Okayyy... I'm not screaming red flag, but I am raising one eyebrow. 👀";
  const advice = features.his_investment === 'WAY TOO MUCH' || features.reciprocity === 'Mostly me' ? 'Your move right now is not to try harder. Give this enough room to show you what it actually is.' : low ? 'Nothing here needs fixing right now. Enjoy the good energy and keep living your life.' : features.meetings === 0 ? 'Online chemistry is cute, but real-life consistency tells you more. Keep expectations proportional.' : 'Match the energy for now. Let them show you what they are willing to meet you with.';
  return <main className="results-page"><div className="results-intro"><span className="kicker">THE RECEIPTS ARE IN</span><h1>{intro}</h1><p>{low ? 'Bestie, I fear we may have found basic healthy communication. Revolutionary. 😭💚' : 'The data is leaning somewhere, but similarity does not equal destiny.'}</p></div><section className={`result-hero ${warning.toLowerCase()}`}><div className="result-icon"><Avatar mood={low ? 'positive' : high ? 'ghost' : 'concern'} /></div><div><span className="result-label">{high ? '🚩 HIGH PATTERN MATCH' : low ? '💚 LOW WARNING' : '⚠️ MIXED SIGNALS DETECTED'}</span><h2>{result.negative_cases} of {result.total_similar_cases} closest situations ended negatively.</h2><p>The biggest recurring pattern? <strong>{patternNames[result.common_pattern] || result.common_pattern}</strong></p></div></section><div className="result-columns"><section className="result-card score-card"><span className="kicker">SIMILARITY CHECK</span><strong className="big-score">{Math.round(result.similar_cases?.[0]?.similarity || 0)}<small>%</small></strong><p>shares details with the historical cases we matched. Familiar does not mean inevitable.</p><div className="ratio"><span style={{ width: `${(result.negative_ratio || 0) * 100}%` }} /></div><small>{result.negative_cases} negative outcomes in the closest {result.total_similar_cases} matches</small></section><section className="result-card advice-card"><Sparkles size={20} /><span className="kicker">MY BESTIE TAKE</span><h2>{advice}</h2><p>Watch the pattern without making it your entire storyline. Go live your own life, queen. 💅</p></section></div><section className="similar-cases"><div><span className="kicker">THE RECEIPTS</span><h2>Cases that look suspiciously similar.</h2></div>{result.similar_cases?.map((item) => <div className="case-row" key={item.case_id}><span>CASE #{item.case_id.replace('G', '')}</span><strong>{patternNames[item.pattern] || item.pattern}</strong><b>{item.similarity}%</b><em>{outcomeNames[item.outcome] || item.outcome}</em></div>)}</section><p className="disclaimer">These are similarities to previous situations, not predictions of what someone will do. People are not algorithms. 💗</p><button className="button button-primary result-reset" onClick={onReset}><RotateCcw size={16} /> Start another story</button></main>;
}

function ProfileSetup({ profile, onSave, onBack }) {
  const [draft, setDraft] = useState(profile);
  return <main className="workspace-page"><button className="back-button" onClick={onBack}><ChevronLeft size={16} /> back</button><section className="setup-panel"><Avatar mood="positive" /><span className="kicker">LET'S GET TO KNOW YOU</span><h1>Small context. Better questions.</h1><p>This stays in your current demo session and helps Bro Mode remember what matters to you.</p><label>Your name<input value={draft.name === 'friend' ? '' : draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value || 'friend' })} placeholder="What should I call you?" /></label><label>What is your current situation<select value={draft.relationshipStatus} onChange={(event) => setDraft({ ...draft, relationshipStatus: event.target.value })}><option value="talking to someone">I am talking to someone</option><option value="complicated">It is complicated</option><option value="moving on">I am moving on</option><option value="curious">Just curious</option></select></label><label>When you like someone, you usually...<select value={draft.interactionStyle} onChange={(event) => setDraft({ ...draft, interactionStyle: event.target.value })}><option>goes all in when they like someone</option><option>take it slow</option><option>need clarity quickly</option><option>keep my feelings private</option></select></label><div className="tone-picker"><span className="kicker">YOUR TONE</span><div>{['gentle', 'straightforward', 'bro', 'calm'].map((tone) => <button className={draft.tone === tone ? 'active' : ''} key={tone} onClick={() => setDraft({ ...draft, tone })}>{tone}</button>)}</div></div><button className="button" onClick={() => onSave(draft)}>Save my context <ArrowRight size={16} /></button></section></main>;
}

function Dashboard({ profile, onMode, onProfile, stories }) {
  return <main className="dashboard-page"><div className="dashboard-heading"><div><span className="kicker">PATTERN · PRIVATE SPACE</span><h1>{getGreeting(profile)}</h1><p>Your story is yours. We will separate what happened from what it might mean.</p></div><button className="profile-button" onClick={onProfile}>edit profile</button></div><section className="mode-grid">{modeChoices.map((choice) => <button className="mode-card" key={choice.id} onClick={() => onMode(choice.id)}><span>{choice.icon}</span><strong>{choice.title}</strong><small>{choice.description}</small><ArrowRight size={16} /></button>)}</section><section className="dashboard-band"><div><span className="kicker">YOUR STORIES</span><h2>Keep the thread.</h2></div>{stories.length ? stories.slice(0, 3).map((story) => <div className="story-mini" key={story.createdAt}><span>💗</span><strong>{story.title}</strong><small>{story.analysis?.pattern || 'Story saved privately'}</small></div>) : <div className="empty-story"><span>🫶</span><p>No saved stories yet. Your first one can start with one honest sentence.</p></div>}</section><section className="insight-band"><span className="kicker">PATTERN OF THE WEEK</span><h2>Repeated behavior usually tells us more than one isolated event.</h2><p>One delayed reply is an event. A repeated change in communication is information worth discussing.</p></section></main>;
}

function StoryMode({ profile, onStart, onBack }) {
  const [story, setStory] = useState('');
  return <main className="workspace-page"><button className="back-button" onClick={onBack}><ChevronLeft size={16} /> back</button><section className="story-panel"><div className="story-panel-top"><span className="kicker">YOUR STORY 💌</span><span className="heart-progress">🤍 → 💗 → ❤️</span></div><h1>Start wherever you want.</h1><p>{getGreeting(profile)} Tell it like you would tell a smart friend.</p><textarea value={story} onChange={(event) => setStory(event.target.value)} placeholder="Okay bro, here's what happened..." /><div className="story-actions"><button className="button" disabled={!story.trim()} onClick={() => onStart(story)}>Tell it naturally <ArrowRight size={16} /></button><button className="secondary-button" onClick={() => onStart('')}>🧩 Give me questions</button></div><small>Facts first. Interpretations second. No mind-reading here.</small></section></main>;
}

function EvidenceWorkspace({ features, profile, result, onAnalyze, onReality, onOverthink, onDecision, onSave, onBack }) {
  const analysis = deriveBroAnalysis(features, profile); const timeline = buildTimeline(features, profile); const [notes, setNotes] = useState('');
  return <main className="evidence-page"><div className="evidence-header"><button className="back-button" onClick={onBack}><ChevronLeft size={16} /> dashboard</button><span className="heart-state">{analysis.healthy ? '💗' : analysis.concernCount > 2 ? '💓' : '❤️'}</span><span className="kicker">WHAT'S ACTUALLY GOING ON?</span><h1>Okay. Let me put the pieces together.</h1><p>Here is what you told me, without pretending it reveals someone else's inner world.</p></div><section className="timeline-card"><span className="kicker">YOUR STORY</span>{timeline.map((event, index) => <motion.div className="timeline-item" key={`${event}-${index}`} initial={{ opacity: 0, x: -8 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: index * .07 }}><span>{index === timeline.length - 1 ? '❤️' : '↓'}</span><strong>{event}</strong></motion.div>)}</section><section className="fact-grid"><div className="fact-card"><span className="kicker">WHAT WE KNOW</span>{analysis.facts.map((fact) => <p key={fact}>✓ {fact}</p>)}</div><div className="fact-card assumption"><span className="kicker">WHAT WE'RE ASSUMING</span><p>Possible explanations are not evidence of intention.</p><p>We cannot know what they feel without them saying it.</p></div><div className="fact-card unknown"><span className="kicker">WHAT WE DON'T KNOW</span>{analysis.unknowns.map((item) => <p key={item}>? {item}</p>)}</div></section><section className="pattern-found"><span className="kicker">PATTERN FOUND</span><h2>{analysis.pattern}</h2><p>{analysis.interpretation}</p><div className="flag-row"><span className={analysis.healthy ? 'green-flag' : 'yellow-flag'}>{analysis.healthy ? '🟢 GREEN · observable reciprocity' : analysis.concernCount > 2 ? '🔴 RED · repeated concern signals' : '🟡 YELLOW · worth discussing'}</span><span>One-time event ≠ repeated pattern</span></div></section><section className="bro-tools"><button onClick={onReality}>🪞 Give me a reality check</button><button onClick={onOverthink}>🧠 Am I overthinking this?</button><button onClick={onAnalyze}>🔍 Compare historical patterns</button><button onClick={onDecision}>🧭 What should I do?</button></section><section className="private-notes"><div><span className="kicker">PRIVATE NOTES</span><h2>What I wish I could say...</h2></div><textarea value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="This stays personal and is not used as an ML feature." /><button className="secondary-button" onClick={() => localStorage.setItem('pattern-private-note', notes)}>SAVE PRIVATELY</button></section><button className="button" onClick={() => onSave({ title: profile.name === 'friend' ? 'A story I wanted to understand' : `A story for ${profile.name}`, analysis, features })}>Save this story <ArrowRight size={16} /></button>{result && <p className="saved-note">Historical pattern analysis is ready below.</p>}</main>;
}

function DecisionRoom({ analysis, onBack }) {
  const options = getDecisionOptions(analysis); const [selected, setSelected] = useState(null); const [path, setPath] = useState([]);
  return <main className="decision-page"><button className="back-button" onClick={onBack}><ChevronLeft size={16} /> back to evidence</button><span className="kicker">BRO MODE · WHAT SHOULD I DO?</span><h1>Okay bro. Here's where you are.</h1><p className="decision-lede">{analysis.interpretation}</p><h2>You have a few options.</h2><div className="decision-options">{options.map((option, index) => <button className={`decision-option option-${index}`} key={option.id} onClick={() => { setSelected(option); setPath([]); }}><b>OPTION {index + 1}</b><strong>{option.title}</strong><small><em>Best when:</em> {option.bestWhen}</small><small><em>Benefit:</em> {option.benefit}</small><small><em>Possible downside:</em> {option.downside}</small></button>)}</div>{selected && <section className="simulator"><span className="kicker">🧭 LET'S PLAY THIS OUT</span><h2>You decide to {selected.title.toLowerCase()}.</h2><p className="hypothetical">Hypothetical scenario — not a prediction of what will actually happen.</p>{simulateDecision(selected.id).map((step, index) => <motion.div className="sim-step" key={step.day} initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: index * .12 }}><b>{step.day}</b><span>{path[index] || step.text}</span>{index === path.length && <button onClick={() => setPath([...path, step.text])}>continue <ArrowRight size={14} /></button>}</motion.div>)}<button className="secondary-button" onClick={() => setSelected(null)}>Choose another direction</button></section>}</main>;
}

function RealityCheck({ features, onBack, overthinking = false }) { const check = getOverthinkingCheck(features); return <main className="decision-page"><button className="back-button" onClick={onBack}><ChevronLeft size={16} /> back to evidence</button><span className="kicker">{overthinking ? '🧠 CLARITY CHECK' : '🪞 REALITY CHECK'}</span><h1>{overthinking ? 'Let us separate the signal from the spiral.' : 'Here is the honest version.'}</h1><section className="reality-card"><h2>What happened</h2><p>{check.known.join(' ')}</p><h2>How it may have felt</h2><p>It may have felt like they did not care. Your confusion makes sense given the change you described.</p><h2>What we can actually conclude</h2><p>{check.conclusion}</p></section><div className="fact-grid compact-facts"><div><span className="kicker">WHAT WE KNOW</span>{check.known.map((item) => <p key={item}>{item}</p>)}</div><div><span className="kicker">WHAT WE'RE ASSUMING</span>{check.assuming.map((item) => <p key={item}>{item}</p>)}</div><div><span className="kicker">WHAT WE DON'T KNOW</span>{check.unknown.map((item) => <p key={item}>{item}</p>)}</div></div></main>; }

function App() {
  const [view, setView] = useState('intro'); const [profile, setProfile] = useState(() => JSON.parse(localStorage.getItem('pattern-profile') || 'null')); const [features, setFeatures] = useState(null); const [openingMessage, setOpeningMessage] = useState(''); const [result, setResult] = useState(null); const [stories, setStories] = useState(() => JSON.parse(localStorage.getItem('pattern-stories') || '[]'));
  const startChat = (choice = '') => { const opening = choice ? getOpeningChoice(choice) : { inferred: {} }; setFeatures({ ...emptyFeatures, ...opening.inferred }); setOpeningMessage(choice); setView('chat'); window.scrollTo(0, 0); };
  const startDemo = () => { setProfile(demoStory.profile); setFeatures({ ...emptyFeatures, approach_method: 'Friend', conversation_stage: 'Talking regularly', initial_yes: 'YES', reply_change: 'Getting slower', reciprocity: 'Mostly me', mixed_signals: 'NO', relationship_status: 'Single', his_investment: 'High', days_talking: 30, meetings: 1, he_increased_pursuit: 'No' }); setView('evidence'); };
  const finishChat = (data) => { setFeatures(data); setView('evidence'); };
  const runAnalysis = async () => { setView('loading'); const [analysis] = await Promise.all([analyzeSituation(features), new Promise((resolve) => window.setTimeout(resolve, 3100))]); setResult(analysis); setView('results'); };
  const saveCurrent = (story) => { saveStory(story); setStories(JSON.parse(localStorage.getItem('pattern-stories') || '[]')); };
  const shell = (content) => <><PixelDecor /><header className="site-nav"><button className="brand brand-button" onClick={() => setView('home')}><span className="brand-heart">♥</span> PATTERN</button><span className="nav-mode">private demo mode · <button onClick={() => setView('profile')}>profile</button></span></header>{content}</>;
  if (view === 'intro') return <IntroFlow existingProfile={profile} onDemo={startDemo} onComplete={(next) => { setProfile(next); localStorage.setItem('pattern-profile', JSON.stringify(next)); setView('home'); }} />;
  if (view === 'home') return shell(<Dashboard profile={profile || defaultProfile} stories={stories} onProfile={() => setView('profile')} onMode={(mode) => mode === 'demo' ? startDemo() : mode === 'happened' ? setView('story') : startChat(mode === 'confused' ? "I'm confused about the vibes" : '')} />);
  if (view === 'profile') return shell(<ProfileSetup profile={profile} onBack={() => setView('home')} onSave={(next) => { setProfile(next); localStorage.setItem('pattern-profile', JSON.stringify(next)); setView('home'); }} />);
  if (view === 'story') return shell(<StoryMode profile={profile} onBack={() => setView('home')} onStart={(story) => startChat(story)} />);
  if (view === 'chat') return shell(<Chat initialFeatures={features || emptyFeatures} openingMessage={openingMessage} onDone={finishChat} onCancel={() => setView('home')} />);
  if (view === 'evidence') return shell(<EvidenceWorkspace features={features || emptyFeatures} profile={profile} result={result} onAnalyze={runAnalysis} onReality={() => setView('reality')} onOverthink={() => setView('overthink')} onDecision={() => setView('decision')} onSave={saveCurrent} onBack={() => setView('home')} />);
  if (view === 'reality' || view === 'overthink') return shell(<RealityCheck features={features || emptyFeatures} overthinking={view === 'overthink'} onBack={() => setView('evidence')} />);
  if (view === 'decision') return shell(<DecisionRoom analysis={deriveBroAnalysis(features || emptyFeatures, profile)} onBack={() => setView('evidence')} />);
  if (view === 'ready') return shell(<main className="ready-page"><Avatar mood="neutral" /><span className="kicker">I THINK I HAVE THE PICTURE</span><h1>Okay babe... one last pause before we run the receipts.</h1><p>I will compare the pattern you described with historical situations. No destiny claims, no dramatic courtroom music.</p><button className="button" onClick={runAnalysis}>RUN THE RECEIPTS <ArrowRight size={17} /></button><button className="text-button" onClick={() => setView('chat')}>Wait, I forgot something</button></main>);
  if (view === 'loading') return shell(<Loading features={features} onComplete={() => {}} />);
  return shell(<><Results result={result} features={features || emptyFeatures} onReset={() => setView('home')} /><button className="floating-bro" onClick={() => setView('decision')}>🫱 If I were your bro...</button></>);
}

export default App;
